### main  page
GET http://localhost:3000/

### register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@admin.qq",
  "telephone": "866666",
  "password": "123456"
}

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "mike@bond.com",
  "password": "123456"
}

### Get all products
GET http://localhost:3000/api/products

### Get single product
GET http://localhost:3000/api/products/45

### Get all cities
GET http://localhost:3000/api/cities

### Get single product comments
GET http://localhost:3000/api/comments/1

### create new comment
POST http://localhost:3000/api/comments
Content-Type: application/json

{
  "productID": 1,
  "content": "good comment 1",
  "userID": 1
}

### Get users Count
GET http://localhost:3000/api/auth/users-count

### Get products data 
GET http://localhost:3000/api/products-data